### ISSUE TITLE
Investigate suitability of RNTuple interfaces and functionality for CMS with NanoAOD output module

### ISSUE THREAD

**Issue by dan131riley** [makortel/framework#103]
With Jakob Blomer, supervise IRIS-HEP fellow Max Orok in developing a prototype NanoAOD-like output module using RNTuple interfaces

Overall plan and progress
- [x] Creation of a new CMSSW output module skeleton that takes event data as an input and produces an empty ROOT file as an output
- [x] Implementation of the nanoAOD event data model using RNTuple classes
- [x] Implementation of the nanoAOD auxiliary data output
- [x] Integration into CMSSW, PR cms-sw/cmssw#33825
- [ ] #116 
- [ ] Backfill support through RNTuple friend mechanism
- [ ] Complete support for NanoAOD auxiliary trees
- [ ] Implementation of parallel RNTuple writing based on event clusters
- [ ] Unit tests and relval workflow
- [ ] Documentation

**Comment by dan131riley** [comment]
Copied from the project plan by @mxxo:

- [ ] Creation of a new CMSSW output module skeleton that takes event data as an input and produces an empty ROOT file as an output
- [ ] Implementation of the nanoAOD event data model using RNTuple classes
- [ ] Implementation of the nanoAOD auxiliary data output
- [ ] Implementation of parallel RNTuple writing based on event clusters
- [ ] Documentation, testing, and first measurements

**Comment by dan131riley** [comment]
RFC PR: https://github.com/cms-sw/cmssw/pull/33825

**Comment by makortel** [comment]
Superseded by https://github.com/makortel/framework/issues/592
