### ISSUE TITLE
Investigate igprof accounting with TBB change

### ISSUE THREAD

**Issue by gartung** [makortel/framework#111]
https://github.com/cms-sw/cmssw/issues/33297
https://github.com/igprof/igprof/issues/86
https://github.com/oneapi-src/oneTBB/issues/384#event-4656961859
This patch for igprof seems to resolve the undercounting problem.
cms-externals/igprof#2

**Comment by gartung** [comment]
@gartung

**Comment by gartung** [comment]
@gartung self assigned does not show up in notifications

**Comment by gartung** [comment]
@makortel can you assign this to me

**Comment by makortel** [comment]
@gartung, this work is now complete, right?

**Comment by gartung** [comment]
Yes
