### ISSUE TITLE
Debug and Fix assert failure in edm::BranchIDListHelper::fixBranchListIndexes

### ISSUE THREAD

**Issue by wddgit** [makortel/framework#140]
Fix the following problem reported on the Framework hypernews

#3  0x00007f8b781f39c9 in sig_dostack_then_abort () from /cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_10_6_24/lib/slc7_amd64_gcc820/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00007f8b7c69a387 in raise () from /lib64/libc.so.6
#6  0x00007f8b7c69ba78 in abort () from /lib64/libc.so.6
#7  0x00007f8b7c6931a6 in __assert_fail_base () from /lib64/libc.so.6
#8  0x00007f8b7c693252 in __assert_fail () from /lib64/libc.so.6
#9  0x00007f8b7f7b6966 in edm::BranchIDListHelper::fixBranchListIndexes(std::vector<unsigned short, std::allocator<unsigned short> >&) const () from /cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_10_6_24/lib/slc7_amd64_gcc820/libDataFormatsProvenance.so
#10 0x00007f8b6a001340 in edm::RootFile::fillEventHistory() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_10_6_24/lib/slc7_amd64_gcc820/pluginIOPoolInput.so
#11 0x00007f8b6a0016bb in edm::RootFile::readCurrentEvent(edm::EventPrincipal&) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_10_6_24/lib/slc7_amd64_gcc820/pluginIOPoolInput.so
#12 0x00007f8b6a0017e0 in edm::RootFile::readEvent(edm::EventPrincipal&) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_10_6_24/lib/slc7_amd64_gcc820/pluginIOPoolInput.so
#13 0x00007f8b69fd96ee in edm::PoolSource::readEvent_(edm::EventPrincipal&) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_10_6_24/lib/slc7_amd64_gcc820/pluginIOPoolInput.so
#14 0x00007f8b7f5f2a1b in decltype ({parm#1}()) edm::convertException::wrap<void edm::callWithTryCatchAndPrint<void>(std::function<void ()>, char const*, bool)::{lambda()#1}>(void edm::callWithTryCatchAndPrint<void>(std::function<void ()>, char const*, bool)::{lambda()#1}) () from /build/wdd/reldebug/CMSSW_10_6_24/lib/slc7_amd64_gcc820/libFWCoreFramework.so
#15 0x00007f8b7f5f2b1c in void edm::callWithTryCatchAndPrint<void>(std::function<void ()>, char const*, bool) () from /build/wdd/reldebug/CMSSW_10_6_24/lib/slc7_amd64_gcc820/libFWCoreFramework.so
#16 0x00007f8b7f5f0d00 in edm::InputSource::readEvent(edm::EventPrincipal&, edm::StreamContext&) () from /build/wdd/reldebug/CMSSW_10_6_24/lib/slc7_amd64_gcc820/libFWCoreFramework.so
#17 0x00007f8b7f60b39c in edm::EventProcessor::readEvent(unsigned int) () from /build/wdd/reldebug/CMSSW_10_6_24/lib/slc7_amd64_gcc820/libFWCoreFramework.so
#18 0x00007f8b7f60cf8b in edm::EventProcessor::readNextEventForStream(unsigned int, edm::LuminosityBlockProcessingStatus&) () from /build/wdd/reldebug/CMSSW_10_6_24/lib/slc7_amd64_gcc820/libFWCoreFramework.so
#19 0x00007f8b7f60d2c3 in edm::SerialTaskQueue::QueuedTask<void edm::SerialTaskQueueChain::push<edm::EventProcessor::handleNextEventForStreamAsync(edm::WaitingTaskHolder, unsigned int)::{lambda()#1}>(edm::EventProcessor::handleNextEventForStreamAsync(edm::WaitingTaskHolder, unsigned int)::{lambda()#1}&&)::{lambda()#1}>::execute() () from /build/wdd/reldebug/CMSSW_10_6_24/lib/slc7_amd64_gcc820/libFWCoreFramework.so
#20 0x00007f8b7dda37a1 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7f8b7974f200, parent=..., child=<optimized out>) at ../../src/tbb/scheduler.cpp:1020
#21 0x00007f8b7f60a945 in edm::EventProcessor::processLumis(std::shared_ptr<void> const&) () from /build/wdd/reldebug/CMSSW_10_6_24/lib/slc7_amd64_gcc820/libFWCoreFramework.so
#22 0x00007f8b7f612ebe in edm::EventProcessor::runToCompletion() () from /build/wdd/reldebug/CMSSW_10_6_24/lib/slc7_amd64_gcc820/libFWCoreFramework.so
#23 0x0000000000410c7b in main::{lambda()#1}::operator()() const ()
#24 0x000000000040f2e2 in main ()

**Comment by makortel** [comment]
Done in https://github.com/cms-sw/cmssw/pull/33736

**Comment by wddgit** [comment]
Fix was merged into CMSSW
