### ISSUE TITLE
Make DBG builds great again

### ISSUE THREAD

**Issue by dan131riley** [makortel/framework#142]
DBG builds are currently nearly total failures, due to code that doesn't compile with optimization off and code that doesn't compile with EDM_ML_DEBUG defined.

- [x] CondTools/Ecal
- [x] L1Trigger/CSCTrackFinder
- [x] L1Trigger/DTTriggerPhase2
- [x] SimTransport/PPSProtonTransport
- [x] Validation/HGCalValidation

**Comment by Dr15Jones** [comment]
See cms-sw/cmssw/#33737

**Comment by Dr15Jones** [comment]
See cms-sw/cmssw#33739

**Comment by Dr15Jones** [comment]
See cms-sw/cmssw#33740

**Comment by Dr15Jones** [comment]
See cms-sw/cmssw#33741

**Comment by mrodozov** [comment]
https://github.com/cms-sw/cmssw/pull/33719
