### ISSUE TITLE
Add FinalPath

### ISSUE THREAD

**Issue by makortel** [makortel/framework#322]
* May contain only OutputModules
* To be run after all other EDModules have been run
* Does not trigger prefetching

See https://github.com/cms-sw/cmssw/issues/36138

Done in https://github.com/cms-sw/cmssw/pull/36398

Backported to 12_2_X in https://github.com/cms-sw/cmssw/pull/36438

**Comment by Dr15Jones** [comment]
@makortel I assume we also need the ability to apply `and` filters based on Paths to OutputModules as well?

**Comment by makortel** [comment]
I assumed that would not be necessary, but I'll ask explicitly.

**Comment by makortel** [comment]
Can `SelectEvents` of OutputModule be used for EndPaths?

**Comment by Dr15Jones** [comment]
> Can SelectEvents of OutputModule be used for EndPaths?

I do not think so. I do not believe we record the status of EndPaths anywhere.

**Comment by makortel** [comment]
> I assume we also need the ability to apply `and` filters based on Paths to OutputModules as well?

https://github.com/cms-sw/cmssw/issues/36138#issuecomment-975756876 confirms that this feature would not be needed for the HLT use case.
