### ISSUE TITLE
Performance tests on Perlmutter

### ISSUE THREAD

**Issue by makortel** [makortel/framework#327]
- [ ] Scan total throughput vs total memory by filling up a node, varying number of threads per process. Keep number of streams the same as the number of threads.
- [ ] With the "best working point", scan total throughput by decreasing the number of streams in a job to see when if starts to affect the throughput

**Comment by makortel** [comment]
Let's try to use the latest 12_2_0_pre3.

**Comment by gartung** [comment]
@makortel Can I close this?
