### ISSUE TITLE
tbb::task_group: test use of resumable task API

### ISSUE THREAD

**Issue by Dr15Jones** [makortel/framework#36]
- [x] write test using resumable task API
- [x] create an issue to oneTBB
- [x] get response to issue

**Comment by Dr15Jones** [comment]
See: https://github.com/oneapi-src/oneTBB/issues/346

**Comment by makortel** [comment]
Comment in https://github.com/oneapi-src/oneTBB/issues/346 instructed to use `task_group::defer_task`, which was done in https://github.com/makortel/framework/issues/414
