### ISSUE TITLE
Add generic support for having different versions (portability backends) for EDModules

### ISSUE THREAD

**Issue by makortel** [makortel/framework#392]
Some earlier discussion in https://github.com/cms-sw/cmssw/issues/35516#issuecomment-962763050

**Comment by makortel** [comment]
Short notes from discussion earlier today
* We could use the EDModule name (`cms.EDProducer("FooProducer@something")`) to specify the backend (automatic vs. specific)
* Or we could add an untracked parameter for that (we'd probably anyway need to deliver the chosen version via untracked parameter)

**Comment by Dr15Jones** [comment]
Notes from a quick code check:
- MakeModuleParams could hold which accelerators should be used for this job
- edm::Factory takes the MakeModuleParams and could use the accelerator info if the module type name contains the special 'key'
- Just have to be sure to register the proper module accelerator type with the proper key.
