### ISSUE TITLE
Avoid short-circuiting ESWatchers

### ISSUE THREAD

**Issue by makortel** [makortel/framework#473]
Done in

- [x] https://github.com/cms-sw/cmssw/pull/40297
- [x] https://github.com/cms-sw/cmssw/pull/40300
- [x] https://github.com/cms-sw/cmssw/pull/40302
- [x] https://github.com/cms-sw/cmssw/pull/40303

**Comment by perrotta** [comment]
@makortel all PRs listed in this issue have been now merged in the master
