### ISSUE TITLE
Remove static analyzer checks related to EventSetupRecord::get() 

### ISSUE THREAD

**Issue by makortel** [makortel/framework#479]
All calls to `EventSetupRecord::get()` have been removed, so the checker has served well its purpose and can be cleaned out. At that time also the specific report page in IB dashboard should also be cleaned out.

- [x] Remove link from dashboard https://github.com/cms-sw/cmssdt-ib/pull/25
- [x] Unregister the checker from the static analyzer https://github.com/cms-sw/cmssw/pull/40462
- [x] Remove references to `eventsetuprecord-get*` from cms-bot https://github.com/cms-sw/cms-bot/pull/1911

The checker code itself is left alive for now (has potentially useful examples for future checkers)

**Comment by gartung** [comment]
https://github.com/cms-sw/cmssdt-ib/pull/25 remove link from dashboard

**Comment by gartung** [comment]
https://github.com/cms-sw/cmssw/pull/40462 unregister checker for EventSetupRecord::get calls.

**Comment by gartung** [comment]
https://github.com/cms-sw/cms-bot/pull/1911 remove references to eventsetuprecord-get.*
