### ISSUE TITLE
Make framework job report to contain failure unless the job succeeds up do "end of main()"

### ISSUE THREAD

**Issue by makortel** [makortel/framework#514]
See discussion in https://github.com/dmwm/CRABServer/issues/7571

The exact definition of when to mark the job as success in FJR needs to be figured out. Especially if the job fails after `main()` has ended, the FJR should report success.

Done in https://github.com/cms-sw/cmssw/pull/41124

To be backported after round of RelVals to

- [x] 13_0_X https://github.com/cms-sw/cmssw/pull/42576
- [x] 12_6_X https://github.com/cms-sw/cmssw/pull/42577

**Comment by makortel** [comment]
Make it active again and do the backports

**Comment by Dr15Jones** [comment]
See https://github.com/cms-sw/cmssw/pull/42576
