### ISSUE TITLE
Add esConsumes calls to ED modules used in production

### ISSUE THREAD

**Issue by Dr15Jones** [makortel/framework#60]
- [ ]  identify which modules are using old API
   - [ ] create list of just production modules 
- [ ] update modules

**Comment by Dr15Jones** [comment]
Associated: #61 #62

**Comment by makortel** [comment]
- [ ] Confirm full matrix works
- [ ] Close the milestone
- [ ] Create new milestone for the tail (that is not run in IBs)

**Comment by makortel** [comment]
All tests of CMSSW_12_3_X_2021-12-13-1100 (first IB with the esConsumes enforced) succeeded.
