### ISSUE TITLE
Release process ParameterSet after EventProcessor construction

### ISSUE THREAD

**Issue by makortel** [makortel/framework#617]
See description of https://github.com/cms-sw/cmssw/pull/42503

Investigate and address `ParameterSet` being held by reference
- [x] #615
- [x] #621
- [x] #623
- [x] #624
- [x] #625
- [x] #620
- [x] #626
- [x] #627
- [x] #628
- [x] #629
- [x] #630
- [x] #631
- [x] #632

Investigate and address `ParameterSet` being held by pointer
- [x] #644
- [x] #645
- [x] #646
- [x] #647
- [x] #649
- [x] #648
- [x] #650

After everything above has been migrated
- [x] #616

Fix IB failures following the merge
- [x] #684
- [x] #685

After the PR above has been merged
- [x] #682
- [x] #683

**Comment by wddgit** [comment]
FYI: cms-sw/cmssw#42536 fixes the two Reco* items. Still under review at the moment.

**Comment by wddgit** [comment]
There are now 3 open PRs that resolve all 6 of the unresolved items on the list. Nothing more to do until those PRs are merged.
