### ISSUE TITLE
Replace reference to ParameterSet with explicit parameter values in `PhysicsTools/UtilAlgos/interface/CachingVariable.h`

### ISSUE THREAD

**Issue by makortel** [makortel/framework#627]

**Comment by wddgit** [comment]
It took me a while to dig through this "CachingVariable" code, but as far as I can see the reference to a ParameterSet is always referring to a ParameterSet object that is independent of the one held by the Framework. The objects are made on the stack, sometimes a copy and sometimes just created from scratch. That means nothing needs to be done here.

As a side note (just an impression I had and I'm quite possibly wrong), but this had the appearance of being code that has been obsolete for years, maybe not used anymore. Then again maybe there are some data analyzers who are there doing analysis with it and writing papers. It's hard to know for sure...
