### ISSUE TITLE
Investigate ParameterSet being held by pointer in DQM

### ISSUE THREAD

**Issue by makortel** [makortel/framework#644]
Inspect the files

- [x] `DQM/HLTEvF/plugins/HLTObjectMonitor.cc`
- [x] `DQM/HLTEvF/plugins/HLTObjectMonitorProtonLead.cc`
- [x] `DQM/L1TMonitorClient/interface/L1TOccupancyClient.h`

and either migrate to something else, or explain here why the pattern is safe

**Comment by wddgit** [comment]
Nothing needs to be done for any of these 3 items. In all 3 cases, these are pointers to ParameterSets that are by value members of the class. They do not point into ProcessDesc.
