### ISSUE TITLE
Investigate ParameterSet being held by pointer in FWCore

### ISSUE THREAD

**Issue by makortel** [makortel/framework#645]
Inspect the files

- [x] `FWCore/Framework/interface/EventSetupsController.h`
- [x] `FWCore/Framework/interface/maker/MakeModuleParams.h`
- [x] `FWCore/Framework/interface/maker/WorkerParams.h`
- [x] `FWCore/ServiceRegistry/interface/ServicesManager.h`

and either migrate to something else, or explain here why the pattern is safe

**Comment by wddgit** [comment]
MakeModuleParams and WorkerParams are used while modules are being constructed. All that work is complete early enough that there is no problem as long as the modules don't save a pointer or reference internally.

**Comment by wddgit** [comment]
ServicesManager is OK. These ParameterSets are used as the services are constructed. This is complete very early, well before beginJob, even before module construction and the objects containing the pointers are deleted when that is done so there is no possibility of problems.

**Comment by wddgit** [comment]
All FWCore are OK as long as the ProcessDesc destruction is done after beginJob.

**Comment by makortel** [comment]
Thanks David
