### ISSUE TITLE
Investigate ParameterSet being held by pointer in Fireworks

### ISSUE THREAD

**Issue by makortel** [makortel/framework#646]
Inspect the `Fireworks/FWInterface/src/FWPSetTableManager.h` and either migrate to something else, or explain here why the pattern is safe

**Comment by wddgit** [comment]
All the uses of this pointer seem to point back to the by value copy of a ParameterSet made here:

https://cmssdt.cern.ch/dxr/CMSSW/source/Fireworks/FWInterface/src/FWPSetTableManager.cc#440

So there isn't a problem. Nothing needs to be done. Fireworks is always making a copy before it uses this interface of the looper and I can't see anything else using this looper feature.

**Comment by makortel** [comment]
So the contract is that it is up to the EDLooper implementation itself to own the necessary `ParameterSet` objects passed to `edm::ModuleChanger::changeModule()`, correct?

**Comment by wddgit** [comment]
Yes.

In this case, the looper owns an object that owns an object (through 2 levels of pointers) that owns its own copy of the ParameterSet.

I started to say nothing enforces that, but actually the ParameterSet passed into the looper is const so if you wanted to modify it, then you would have to copy it. And if you didn't want to modify it, then there be no point in using changeModule.
