### ISSUE TITLE
Investigate ParameterSet being held by pointer in GeneratorInterface

### ISSUE THREAD

**Issue by makortel** [makortel/framework#647]
Inspect the files

- [x] `GeneratorInterface/EvtGenInterface/plugins/EvtGen/EvtGenInterface.h`
- [x] `GeneratorInterface/PhotosInterface/interface/PhotosppInterface.h`
- [x] `GeneratorInterface/TauolaInterface/interface/TauolappInterface.h`

and either migrate to something else, or explain here why the pattern is safe

**Comment by wddgit** [comment]
All 3 of these classes, immediately deep copy the ParameterSet. They are not carrying around a pointer into the ProcessDesc ParameterSet. Nothing to be done. Not a problem.
