### ISSUE TITLE
Investigate ParameterSet being held by pointer in HLTrigger

### ISSUE THREAD

**Issue by makortel** [makortel/framework#649]
Inspect the `HLTrigger/HLTcore/interface/HLTConfigData.h` and either migrate to something else, or explain here why the pattern is safe

**Comment by makortel** [comment]
The `HLTConfigData` is used in https://github.com/cms-sw/cmssw/blob/057d04616c0698541c6ed397f7637cf98cec9eda/HLTrigger/HLTcore/interface/HLTConfigDataRegistry.h, which in turn is used in https://github.com/cms-sw/cmssw/blob/057d04616c0698541c6ed397f7637cf98cec9eda/HLTrigger/HLTcore/src/HLTConfigProvider.cc#L115-L151, i.e. the `ParameterSet*` pointers point to data inside `edm::pset::Registry::instance()`.

To my understanding the contents of the `pset::Registry()` are not affected by the destruction of the `ProcessDesc`, and therefore this use is safe. @Dr15Jones @wddgit could you confirm?

**Comment by wddgit** [comment]
I'd have to dive into the code and look. Should I do that now? I don't remember the answer to that.

**Comment by makortel** [comment]
Let's wait first if @Dr15Jones would remember on the top of his head.

**Comment by wddgit** [comment]
After skimming through this and refreshing my memory a little, I believe the ProcessDesc no longer affects the registry after all the registerIt() calls are complete. As far as I can remember, the EventSetupsController sharing code executes the last of the registerIt() calls in a cmsRun process. The rest may all be done even before beginJob. I can't think of any others that occur in beginJob.

**Comment by makortel** [comment]
Thanks, this use of pointer-to-`ParameterSet` should be safe then.
