### ISSUE TITLE
Investigate ParameterSet being held by pointer in PhysicsTools

### ISSUE THREAD

**Issue by makortel** [makortel/framework#650]
Inspect the `PhysicsTools/PatAlgos/plugins/PATTriggerProducer.cc` and either migrate to something else, or explain here why the pattern is safe

**Comment by wddgit** [comment]
The pointer is always null or pointing at a ParameterSet in the registry, not at a ParameterSet owned by ProcessDesc. There should be no problem with that and nothing need to be done.
