### ISSUE TITLE
esConsumes: Investigate possibility of doing a delayed esConsumes call

### ISSUE THREAD

**Issue by Dr15Jones** [makortel/framework#66]
The OscarMTProducer sensitive detector construction would like to see what ideal geometry is being used before deciding the sensitive detectors.

**Comment by Dr15Jones** [comment]
Such a framework task could be launched from Worker::doWorkAsync in a way similar to the handling of prePrefetchSelectionAsync.

**Comment by Dr15Jones** [comment]
In order to use our present data structures to update the esConsumes, we'd also need to generate the `edm::eventsetup::ESRecordsToProxyIndices` objects expected by `EDConsumerBase` to do the lookups. Normally that is created by the `EventSetupProvider` but I'm pretty sure that `EventSetupImpl` could also be used to build one as needed.

**Comment by Dr15Jones** [comment]
So we could add a new module template parameter probably only for stream modules (at least for now)
```C++
namespace edm::stream {
   struct DelayConsumesTillRun {};
   struct DelayConsumesTillLuminosityBlock {};
}
```

Using that would add member functions
```C++
     runDelayedConsumesCollector(); \\ to be called in constructor
     void delayedConsumes(edm::Run const&, edm::EventSetup const&, edm::ConsumesCollector& );
```

I think it would be possible to not only allow esConsumes, but we could probably also do consumes for Run, LuminosityBlock and Events!

**Comment by Dr15Jones** [comment]
A better interface would probably be to use a helper class to make the actual decision and hold the different tokens. The new module template parameter would be something like
```C++
namespace edm::stream {
   struct UseDelayedConsumesCollector {};
}
```
This would add to the module a new member function to be used at construction time
```C++
template<typename DELAYED, typename... F>
std::shared_ptr<DELAYED const> registerDelayedConsumesCollector(F...&&);
```
The function constructs an instance of `DELAYED` which must inherit from `edm::DelayedConsumesCollector` with constructor arguments `F..`.

`edm::DelayedConsumesCollector` inherits from (or has the same public member functions as) `edm::EDConsumerBase`  and therefore one calls `consumes` and/or `esConsumes` in its constructor to state what data must be gotten to make the delayed decision on the rest of the consumed data.

The `DELAYED` class must declare a `decide` public member function with returns `void` and takes as its first argument a `edm::ConsumesCollector`, its second argument must be one of `edm::Run const&`, `edm::LuminosityBlock const&` or `edm::Event const&` and its last arugment is `edm::EventSetup const&`. In that call it uses the tokens it set in its constructor to get the data needed for the decision and then calls `consumes` and/or `esConsumes` on the passed in `edm::ConsumesCollector` to set the tokens to be used by the ED module during its normal transition call. I envision those tokens being a public part of the interface of the `DELAYED` class while the tokens used during `decide` should be private.

**Comment by Dr15Jones** [comment]
As a concrete example, the OscarMTProducer would use a DelayedConsumesCollector something like
```C++
struct OscarDelayedCollector : public DelayedConsumesCollector {
   OscarDelayedCollector(): geomToken_{esConsumes<IdealGeometry, IdealGeometryRecord>()} {}

   void decide(edm::ConsumesCollector iCC, edm::Run const&, edm::EventSetup const& iES) {
      auto const& geom = iES.getData(geomToken_);
      sensitiveGeometryFactories_ = makeFactories(iCC, geom); 
   };
   //The factories know what data they need so did the esConsumes call and are holding the tokens
   std::vector<...> sensitiveGeometryFactories_;
private:
   edm::ESGetToken<IdealGeometry, IdealGeometryRcd> const geomToken_;
};
```

Then during `OscarMTProducer::beginRun` it will use the `OscarDelayedCollector:: sensitiveGeometryFactories_` to use the prefetched EventSetup data products to construct the actual sensitive detectors.

**Comment by makortel** [comment]
Closing as likely not needed feature in the end (`OscarMTProducer` was migrated in a different way).
