### ISSUE TITLE
Add option to do the proper `LD_PRELOAD` to cmsDriver

### ISSUE THREAD

**Issue by makortel** [makortel/framework#671]
The proper `LD_PRELOAD` content is documented in https://github.com/cms-sw/cmssw/blob/master/PerfTools/MaxMemoryPreload/README.md. Presumably it could be handled in runTheMatrix and cmsDriver similary to jeprof (that also needed environment variable to be set)

Done in https://github.com/cms-sw/cmssw/pull/44001

**Comment by antoniovilela** [comment]
https://github.com/cms-sw/cmssw/pull/44001 has been merged
