### ISSUE TITLE
Clean up all files that #include legacy EDModule header

### ISSUE THREAD

**Issue by makortel** [makortel/framework#704]

**Comment by wddgit** [comment]
cms-sw/cmssw#43817 finishes files in simulation

**Comment by wddgit** [comment]
cms-sw/cmssw#43818 finishes files in day

**Comment by wddgit** [comment]
cms-sw/cmssw#43829 finishes files in geometry

**Comment by wddgit** [comment]
cms-sw/cmssw#43832 finishes files in L1

**Comment by wddgit** [comment]
cms-sw/cmssw#43833 finishes files in analysis

That is the last of these PRs except maybe I should also delete FWCore/Utilities/bin/edmConvertToStreamModule.py (still thinking about whether to keep that one).

**Comment by wddgit** [comment]
cms-sw/cmssw#43835 removes FWCore/Utilities/bin/edmConvertToStreamModule.py. All the references to legacy modules that I could find using "git grep" will be removed as soon as all the submitted PR's are merged.
